### ISSUE TITLE
"VocabularyImpl.cpp" missing ?

### ISSUE THREAD

**Issue by horst98** [DanMcLaughlin/antlr4#1]
Hi.

(Thanks for this nice tool.)
I just tried to built it (master / commit e9d2a04be1b0320afe006107e0df70193bfda6d7) with Visual Studio 2015 Update 2. It seems that the file "VocabularyImpl.cpp" (in directory "runtime/Cpp/runtime/src") is missing.
Anyhow this file is listed in the Visual Studio project. (After removing the concerning item the linker fails with not found symbols). I searched the repository with "git log" but couldn't find it.
Could you add it, please, if so?

Thank you.

**Comment by mike-lischke** [comment]
That was a temporary problem when VocabularyImpl was removed. The VS solution had to be updated, which happened in the meantime.
