### ISSUE TITLE
Minimum cmake requirements

### ISSUE THREAD

**Issue by chrisheller** [DanMcLaughlin/antlr4#10]
I had a machine with CMake 3.2.2 on it and received the following error while building. 

```
CMake Error at CMakeLists.txt:28 (CMAKE_POLICY):
  Policy "CMP0059" is not known to this version of CMake.
```

Updating to the current CMake (3.5.2 as of right now) addressed the issue,  although I believe that policy was added to CMake in version 3.3.

**Comment by mike-lischke** [comment]
Fixed by patch #11
