### ISSUE TITLE
CMakeLists

### ISSUE THREAD

**Issue by riccardodebenedictis** [DanMcLaughlin/antlr4#13]
Dear all,

I was trying to compile the c++ runtime on windows (cygwin) and found out the generated makefile is c++98

to solve this issue it was sufficient, for me, to add the following line at beginning of CMakeLists.txt

`set(CMAKE_CXX_STANDARD 11)`

hope that helps!

many, many thanks for your precious work!

**Comment by mike-lischke** [comment]
Thanks. Added in revision [d46ef90]
