### ISSUE TITLE
C++ target doesn't produce C++ files

### ISSUE THREAD

**Issue by nuuman** [DanMcLaughlin/antlr4#2]
I downloaded antlr4-4.5.4-SNAPSHOT.jar from the blog post and ran

    java -jar -Dlanguage=Cpp antlr4-4.5.4-SNAPSHOT.jar Grammar.g4

But it still produces Java files. What am I doing wrong?

**Comment by mike-lischke** [comment]
From where did you download the jar?

**Comment by nuuman** [comment]
From http://www.soft-gems.net/files/antlr4-4.5.4-SNAPSHOT.jar, which was linked to from http://www.soft-gems.net/index.php/tools/49-the-antlr4-c-target-is-here

**Comment by nuuman** [comment]
> Ensure there is no language override in the grammar.

What do you mean? I use the CVS.g4 grammar from https://github.com/antlr/grammars-v4/tree/master/csv as a test.

**Comment by mike-lischke** [comment]
You used the wrong command. The jar must appear directly after -jar. Try this instead: `java -jar antlr4-4.5.4-SNAPSHOT.jar -Dlanguage=Cpp -listener -visitor -o generated/ -package test CSV.g4`

**Comment by nuuman** [comment]
You're right. Thanks for the help.

**Comment by nuuman** [comment]
@mike-lischke stupid question maybe, but the blog post is light on this topic... where is the C++ runtime and headers?  

The Readme.md says prebuilt is on antlr.org, but no C++ targets for download on http://www.antlr.org/download.html

Am I looking at the wrong place?
