### ISSUE TITLE
Exported C++ Has pedantic flaws -> generator creating extra ‘;’ in source

### ISSUE THREAD

**Issue by timoc** [DanMcLaughlin/antlr4#22]
Finally got it building from a fork using a cmake out of tree build (Cmake patches will be forthcoming)

```
In file included from /home/tim/antlr4/runtime/Cpp/demo/Linux/main.cpp:12:0:
/home/tim/antlr4/runtime/Cpp/demo/generated/TParser.h:142:20: warning: extra ‘;’ [-Wpedantic]
     Token* idToken;;
```

**Comment by mike-lischke** [comment]
Yes, the double semicolons are unavoidable. That has to do with how string templates for code generation are called. Please switch off this check.
