### ISSUE TITLE
C++ Generated source has no backreference comment.

### ISSUE THREAD

**Issue by timoc** [DanMcLaughlin/antlr4#23]
I'm trying to figure out what the work-flow would be for creating and debugging a grammar, especially one where the c++ support library/templates may also need some attention.

With this in mind, is there a way to add supporting comments to the generated code? something like
```
//  from grammar file <filename:line> Created for gramar rule <rule> using template - <lib file> 
```
Would make it easier for me to reason about a c++ grammar.

**Comment by mike-lischke** [comment]
Where would you like to see such comments? The generated parser + lexer files use function names which directly correspond to the rules in the grammar. What else would you like to see?

**Comment by timoc** [comment]
I'm only just starting to work with antlr, but i was thinking of something like the C standard pre-processor comments. Most C++ editors would be able to work with them as normal.  Also source comments might be handy too?

**Comment by mike-lischke** [comment]
Sorry, but I still don't see what you would like to have. Can you give me a concrete example and I'll think if that is possible to add to the template file. You can also try yourself btw. Add stuff you want to have printed in source code in the [main template file](tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg).

**Comment by mike-lischke** [comment]
@timoc Is this issue still relevant for you? Can you give me the requested examples or will you do the additions yourself in the template file?
