### ISSUE TITLE
GCC performance significantly worse than MSVC

### ISSUE THREAD

**Issue by nburles** [DanMcLaughlin/antlr4#25]
For the grammar I have created, performance under Linux (GCC 6.1.1) is unbearable, where performance under Windows (MSVC 14 - Visual Studio 2015 with Update 3) is excellent.

For an example input file, parsing in Windows takes ~100 milliseconds... parsing in Linux takes ~30000 milliseconds!

I've done some basic profiling in Linux, and found e.g. the call graph is:

```
Called       Function
995,739,724  antlr4::atn::ATNConfigSet::operator==(antlr4::atn::ATNConfigSet const&)
995,739,724  antlr4::dfa::DFAState::operator==(antlr4::dfa::DFAState const&) const <cycle 1>
  1,958,794  __strcmp_sse2_unaligned
  1,582,031  antlr4::misc::MurmurHash::update(unsigned long, unsigned long)
```

Similarly, the performance report is:
```
Overhead  Command          Shared Object                 Symbol
  66.86%  TM1RulesParserT  libantlr4-ANTLR4cpp.so.4.5.4  [.] antlr4::atn::ATNConfigSet::operator==
  10.12%  TM1RulesParserT  libantlr4-ANTLR4cpp.so.4.5.4  [.] std::_Hashtable<antlr4::dfa::DFAState*, antlr4::dfa::DFAState*, std::allocator<antlr4::dfa::DFAState*>, std::__detail::_Identity, antlr4::dfa::DFAState::Comparer, antlr4::dfa::DFAState::Hasher, std::__detail::_M
  10.06%  TM1RulesParserT  libantlr4-ANTLR4cpp.so.4.5.4  [.] antlr4::atn::LexerATNSimulator::addDFAState
   8.72%  TM1RulesParserT  libantlr4-ANTLR4cpp.so.4.5.4  [.] antlr4::dfa::DFAState::operator==
   1.13%  TM1RulesParserT  libantlr4-ANTLR4cpp.so.4.5.4  [.] _ZNK6antlr43dfa8DFAStateeqERKS1_@plt
   0.88%  TM1RulesParserT  libantlr4-ANTLR4cpp.so.4.5.4  [.] _ZN6antlr43atn12ATNConfigSeteqERKS1_@plt
```

For comparison, when parsing the same file in Visual Studio I found that `antlr4::atn::ATNConfigSet::operator==` was called `855` times!

**Comment by nburles** [comment]
The difference seems to come in `LexerATNSimulator::execATN`... it is called exactly the same number of times in Windows and Linux, but it calls `LexerATNSimulator::computeTargetState` 38,133 times in Linux compared with 554 times in Windows.

So for some reason `getExistingTargetState(s, t)` appears to be failing to find the existing target state and so generation is happening over and over.

**Comment by mike-lischke** [comment]
Did you check whether the computed target state is cached? I have seen the frequent recomputation when there are predicates on the left hand side in a rule (as I wrote in my blog posting). But then it would be slow on all platforms. Try to find out why the computed states are not cached (what I suspect happens actually).

**Comment by nburles** [comment]
I'd seen the blog post, but have no predicates at all so that shouldn't be it.  I'm attempting to step through now and find out more detail as to why it keeps recalculating... `getExistingTargetState(s, t)` does appear to be finding the target sometimes, so I'll keep working on it...

**Comment by nburles** [comment]
I've tracked a bit further... although the ANTLR-generated code is identical between Windows and Linux (save line-endings) - i.e. the Lexer's _serializedATN matches - stepping through the lexing with a breakpoint on `LexerATNSimulator.cpp`::`if (target == nullptr) {` throws up a difference...

For the first 13 characters of the input file the inputs `s` and `t` match (i.e. same current state and same next character).  But at the next break, although the character `t` matches, the state `s` in Linux is incorrect!

Will continue investigating tomorrow...

**Comment by Nic30** [comment]
It can be related with issue #12. (at least it seems to happen in same part of code)
If compiled with gcc there is some bug(s) but I had no time to find out.

**Comment by nburles** [comment]
@Nic30: which version of GCC have you used? If it's the same as mine, it might be worth me testing a different version?

**Comment by Nic30** [comment]
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.1) 
But I have tested 4.9 and 6 as well and it did not solved my issue.

**Comment by nburles** [comment]
Great - just thought it would be worth making sure we're not both just using GCC 6.1.1 so a bug in the latest version can be pretty much ruled out.

**Comment by nburles** [comment]
I've added a serialization step into my lexer, just after the deserialization - with the intention of ensuring that serialized -> deserialized -> serialized returns the original ATN in both Windows and Linux.  It does not in Windows (I haven't yet got to Linux...!)

The initial difference comes right at the beginning... the _serializedATN is encoded as `0x3, 0x430, 0xd6d1, 0x8206, 0xad2d, 0x4417, 0xaef1, 0x8d80, 0xaadd, ...` whereas after deserialization and reserialization, it becomes `0x3, 0xaa, 0xdb, 0x8d, 0x7e, 0xae, 0xef, 0x44, 0x15, ...`.

As the data contains a `SERIALIZED_UUID()` this may be expected (I haven't checked, but could be expected to be different e.g. between the Java ANTLR tool and the C++ ANTLR runtime).

Anyway, I haven't been able to go further down this line as a debug assertion was thrown on line 285 (`arg1 = setIndices[(static_cast<SetTransition *>(t))->set];`)

> Expression: vector iterator + offset out of range

So I'm guessing it's something inside the deserialization that's going wrong (even in Windows apparently)?

**Comment by nburles** [comment]
I haven't tracked down anything as yet, but I did run the reserialization test in the Java target just to be sure... it did work.

**Comment by mike-lischke** [comment]
The ATNSerializer class hasn't been tested at all and likely contains bugs. It's not needed for normal parsing work. I don't even know why it exists in the runtime. The UUIDs shouldn't differ however, they're defined in source code to determine which features are supported in a particular runtime. I'm afraid that serialization test cannot be used to confirm anything related to the original problem. Unless there is something with the used compilers (we had already static init problems with GCC) the unserialized ATN (and the DFA created from it) should be identical on all platforms. I rather suspect ATNState comparisons to be flawed or something like that.
