### ISSUE TITLE
Are mutexes required?

### ISSUE THREAD

**Issue by nburles** [DanMcLaughlin/antlr4#36]
I'm just wondering whether the mutexes / recursive_mutexes are actually needed?  i.e. `<thread>` isn't included anywhere, so given the lexer / parser is single-threaded do we need to synchronize access / etc?

**Comment by mike-lischke** [comment]
There are a number of shared (static) structures (e.g. the DFA), to which access must be synchronized. It's really not much, I believe just 2-3 locks in the entire library. For a single parser it wouldn't matter, but you can have multiple parsers working in different threads.

**Comment by Nic30** [comment]
It means that antrl c++ runtime is thread safe? Are generated parsers as well?

**Comment by mike-lischke** [comment]
No, only shared parts are protected (e.g. the static DFA, which is modified by all parsers of the same type especially during the warmup phases). You cannot use one parser instance in multiple threads, but you can of course use an individual instance per thread.
