### ISSUE TITLE
Grammer rule containing CPP keywords cause issues

### ISSUE THREAD

**Issue by MatthewGM** [DanMcLaughlin/antlr4#37]
Small issue that I am not sure is a runtime issue or just needs to be adapted around in the grammars, but it behaves differently than the Java runtime.

When you use NULL in the grammar as a rule name, the generated code fails to compile.

Example:
In the VisualBasic6 grammar from the main ANTLR repo, there is a NULL keyword, but that, being a reserved word, generates code that won't compile. 

Change NULL to NUL in the grammar instead and all is well.

(As an aside, major props for the project!)

**Comment by mike-lischke** [comment]
This is something we cannot address in the runtime. It's one of the rules when using ANTLR that you cannot use reserved words of your target language as a rule name in the grammar. The same is true for e.g. `false` or `class`.
