### ISSUE TITLE
utf-8 file issue

### ISSUE THREAD

**Issue by nuuman** [DanMcLaughlin/antlr4#4]
My test file contains 

    abc;ф;42

It is utf-8 encoded, and "cat data.csv" shows it correctly on OS X in the terminal.

When I parse and dump the result, the ф (\u0444) displays as garbage.

Code:

    ANTLRFileStream input("data.csv");
    CSVLexer lexer(&input);
    CommonTokenStream tokens(&lexer);
    CSVParser parser(&tokens);

    Ref<tree::ParseTree> tree = parser.file();
    Ref<TreeShapeListener> listener(new TreeShapeListener());
    tree::ParseTreeWalker::DEFAULT.walk(listener.get(), tree);

In the listener, I print the text like below, but the unicode character is displayed as garbage:

    std::cout << ctx->getText().c_str() << std::endl;

The same unicode character displays fine if I print it in an u8 literal.

Ideas?

**Comment by davesisson** [comment]
The internal format of characters in the C++ runtime for Antlr4 is not utf-8.  It's wide characters like in Java.  As a result you'll need to output to wide cout instead:

`std::wcout << ctx->getText().c_str() << std::endl;
`

**Comment by mike-lischke** [comment]
Dave, not entirely true.  The output produced by getText is encoded in UTF-8 (see ANTLRInputStream::getText, from which symbol text is generated).

@nuuman: RuleContext::toString doesn't output terminal node text, so I wonder how you can get garbage there. Try `std::cout << tree->toStringTree(&parser) << std::endl;` instead to print a tree representation including the terminal nodes' texts.

**Comment by nuuman** [comment]
@mike-lischke but I need to dump just a specific field, not the entire tree.

**Comment by nuuman** [comment]
@mike-lischke toStringTree still produces garbage for unicode chars.

@davesisson wcout doesn't work either. As @mike-lischke said, getText is supposed to be utf8.

So please reopen this issue.

**Comment by mike-lischke** [comment]
@nuuman Please create a minimal example that shows your issue, which we can use to reproduce it.

PS: you can edit comments. No need to create multiple ones in a row.

**Comment by nuuman** [comment]
@mike-lischke Any example with utf8 file input should do. Here's how to reproduce:

Generate the CSV.g4 parser from the antlr grammars repository.

I now read the file as follows:

    ANTLRFileStream input("data.csv");
    CSVLexer lexer(&input);
    CommonTokenStream tokens(&lexer);
    CSVParser parser(&tokens);

    Ref<tree::ParseTree> tree = parser.file();
    Ref<TreeShapeListener> listener(new TreeShapeListener());
    tree::ParseTreeWalker::DEFAULT.walk(listener.get(), tree);

This shows garbage (hence, no need to show the listener code, since the below shows the same garbage):

    std::cout << tree->toStringTree(&parser) << std::endl;

Hope this helps.

**Comment by nuuman** [comment]
Sample data.csv with a single unicode character not representable in ascii

    NAME,AGE,ADDRESS
    "Tom",20,"Nowhere ф"

**Comment by nuuman** [comment]
UPDATE: ANTLRFileStream does something really bad.

This works:

    std::ifstream file("input.csv");
    std::stringstream buffer;

    buffer << file.rdbuf();
    std::string str = buffer.str();
    ANTLRInputStream input(str);

I don't understand why the antlr c++ runtime has to do utf conversion internally at all, it should just treat everything as bytes, no? As long as the callee interprets those bytes as utf8, it should be fine.

**Comment by JohnWillow** [comment]
FWIW I'm not having any luck with Unicode input either.

**Comment by mike-lischke** [comment]
I have to admit the ANLTRFileStream has not been tested much. In the demo I use the ANTLRInput stream with emoji input and that works nicely. I have to take a closer look at the file stream.

**Comment by nuuman** [comment]
@mike-lischke thanks for looking into this. Other than this issue, everything looks rock solid so far! Very impressive.

**Comment by JohnWillow** [comment]
@mike-lischke seems like https://github.com/DanMcLaughlin/antlr4/blob/master/doc/cpp-target.md is confused about wifstream as well. ifstream is correct.

**Comment by nuuman** [comment]
Thanks for fixing this so quickly!
