### ISSUE TITLE
Cannot compile due to missing <codecvt> in g++<5.0

### ISSUE THREAD

**Issue by hrjaco** [DanMcLaughlin/antlr4#42]
We are using g++-4.8 and \<codecvt\> is missing there. Any suggestion on how to solve this without upgrading to g++>=5.0?

**Comment by mike-lischke** [comment]
I'm afraid there is no way around upgrading your tool chain. The codecvt header is an official C++11 header and you have to have a compile that supports this fully.

A workaround would be to remove the code that needs codecvt and replace it with something different that allows to convert between utf-8 <-> utf-16 and utf8 -> utf-32.
