### ISSUE TITLE
Optional labels within rules

### ISSUE THREAD

**Issue by riccardodebenedictis** [DanMcLaughlin/antlr4#44]
I have the following grammar rule

`
conjunction
    :   '{' block '}' ('[' cost=expr ']')?;
`

please notice that the `cost` label is optional.

when I parse a "conjunction" _without_ a "cost" I would expect the `cost` field of the conjunction to point to `nullptr` (like in Java) however, surprisingly, this is not the case!

In other words, if i put the following code within a listener:

``` Cpp
enterConjunction(ConjunctionContext * ctx) {
    if (ctx->cost) {
        std::cout << "this code is executed.." << std::endl;
    }
    if (ctx->expr()) {
        std::cout << "this code is not executed.." << std::endl;
    }
}
```

I have the code within the first `if` statement, contrary to what would occur in java, executed.
on the contrary, the code in the second `if` statement is, correctly, _not_ executed.

thank you all for your precious work

**Comment by mike-lischke** [comment]
Is the ctx->cost variable properly initialized to nullptr?

**Comment by riccardodebenedictis** [comment]
I do not initialize it! (should I?)
I would expect the parser doesn't initialize it as well

in other words, both the if conditions of my example should fail (according to my understanding and compared to the Java version)

**Comment by mike-lischke** [comment]
Yes, both should fail and variables should be initialized by the generated parser. It didn't that right from the start, so I wonder if you have a version where it does.

**Comment by riccardodebenedictis** [comment]
I tried it with a simpler grammar (I apologize for not having done it before) and it works as expected..
so I guess I do something weird somewhere.. I wonder what..
nonetheless I guess this issue can be closed..
thank you anyway

**Comment by riccardodebenedictis** [comment]
yet, if I modify the generated code by manually initializing the variable to null (in the initializer list of the conjunction context costructor, which is, maybe, what you were asking earlier) it works..

it looks like that cost variable points to some garbage from the early beginning..

judge for yourself whether or not to close the issue..

**Comment by mike-lischke** [comment]
Ok, so you say there wasn't an initialization, which means you have a jar that doesn't produce the init code for you. I have meanwhile fixed that and will upload a new jar over the next weekend. You can also just build your own jar and use that, however.

**Comment by riccardodebenedictis** [comment]
I have tried with a jar built by myself from latest code
It generates the same code I had (with variables _not_ initialized to null)

I am also using the latest runtime..

**Comment by mike-lischke** [comment]
I updated the jar + sources + prebuilt binaries on my homepage. Hope the update fixes your issue.

**Comment by riccardodebenedictis** [comment]
I confirm that the update fixes my issue!
many thanks

**Comment by mike-lischke** [comment]
Ok, thanks for the feedback!
