### ISSUE TITLE
Error listener garbage output

### ISSUE THREAD

**Issue by nuuman** [DanMcLaughlin/antlr4#5]
Using the CSV grammar parser, I added a very simple error handler:

    class ErrorHandler : public BaseErrorListener
    {
    public:
        virtual void syntaxError(IRecognizer *recognizer, Token * offendingSymbol, size_t line, int charPositionInLine,
                                 const std::string &msg, std::exception_ptr e)
        {
            std::cout << "error occurred: " << std::endl;
            std::cout << msg << std::endl;
        }
    }handler;
    parser.addErrorListener(&handler);

    Ref<tree::ParseTree> tree = parser.file();

Bogus input test file (the - at the beginning)

    NAME,AGE,ADDRESS
    -"Tom",50,"Nowhere"

Error output

    ', ' 2:1 extraneous input '"Tom"' expecting {',', '
    '}
    error occurred:
    ', 'aneous input '"Tom"' expecting {',', '
    '}

This looks wrong.

First of all, 'aneous input' is chopped off. 

Second, shouldn't *only* the error text outputted in the syntaxError handler be displayed, given that an error handler is registered?

**Comment by mike-lischke** [comment]
The extra error output comes from the ConsoleErrorListener which is registered by default. You have first to call removeErrorListeners() before adding your own.

**Comment by nuuman** [comment]
I wasn't aware of this, thanks!

**Comment by nuuman** [comment]
HOWEVER: the text is still cut off:

error occurred:
', 'aneous input '"Tom"' expecting {',', '
'}

**Comment by mike-lischke** [comment]
I cannot reproduce this problem. What I get is:

```
error occurred: 
extraneous input '"Tom"' expecting {',', '
', '
'}
error occurred: 
missing '
' at '<EOF>'
Program ended with exit code: 0

```

**Comment by nuuman** [comment]
I tried again with the latest version on the c++ runtime, using your test case, and I still see the weird output.

I'm compiling with clang on OS X, debug mode.

**Comment by mike-lischke** [comment]
Guess you have to debug yourself then. I can hardly imagine why the text should be cut off at all. You could try to see what comes in your syntaxError() function. If that is the full message then I'd say it's not the failure of the runtime.

**Comment by nuuman** [comment]
Interesting... when I run your test case in iTerm, the output is garbage.

But it's because the error string contains a \r !!!

    00000000  65 78 74 72 61 6e 65 6f  75 73 20 69 6e 70 75 74  |extraneous input|
    00000010  20 27 22 54 6f 6d 22 27  20 65 78 70 65 63 74 69  | '"Tom"' expecti|
    00000020  6e 67 20 7b 27 2c 27 2c  20 27 0d 27 2c 20 27 0a  |ng {',', '.', '.|
    00000030  27 7d 0a                                          |'}.|
    00000033

So when \r (the 0d) is encountered, OS X  terminals will not produce a newline, but just rewind to the current line. That's why ', ' is overwriting the characters on the same line.

So the question is... where the heck does the \r come from?

I have generated the CSV parser from CSV.g4 and made no changes at all, then I used your exact test case.

**Comment by nuuman** [comment]
@mike-lischke, https://github.com/DanMcLaughlin/antlr4/pull/9 solves my specific problem, but it needs to be done more places. I didn't do that job, since I think escapeWSAndQuote should be done at a deeper level.

**Comment by mike-lischke** [comment]
The level is good, as this is all about error reporting. Modifying the strings at a deeper level would make maintenance worse as you would have to keep two variants around (the unaltered and the escaped one).

**Comment by nuuman** [comment]
> Modifying the strings at a deeper level would make maintenance worse as you would have to keep two variants around (the unaltered and the escaped one)

Shows how little I know this code base :) Thanks for merging.
