### ISSUE TITLE
CMake

### ISSUE THREAD

**Issue by nuuman** [DanMcLaughlin/antlr4#6]
There's a cmake file. I tend to use CMake in many projects, and they generate vs.proj, Xcode, unix makefiles with no issues.

Any reason why you can't just distribute a cmake file, instead of Xcode and vs.net project files (which should never, IMO, be committed)

**Comment by mike-lischke** [comment]
Why should I maintain a cmake file when I have my project files? It would just be additional work.

**Comment by nuuman** [comment]
> Why should I maintain a cmake file when I have my project files already? It would just be additional work.

This makes no sense to me. If you have a CMake file, you don't have to maintain *any* projects files (VS.NET, XCode, make, clion, etc, etc)

**Comment by Qix-** [comment]
Err.. yeah. Why are you including both project files and CMake files? You should choose one or the other. Having both creates the potential for them to diverge and will ultimately cause a lot of confused people to come and open tickets.

This is less of a subjective thing and more of a fact. _Subjectively_, however, I suggest the usage of CMake as it has become a bit of a standard anymore.
