### ISSUE TITLE
Binary release fails to link

### ISSUE THREAD

**Issue by nuuman** [DanMcLaughlin/antlr4#7]
I built the first release (june 18) myself on OS X and the CVS example compiled, linked and ran fine.

The binary distribution (static lib) from june 22 fails to link with my application:

    Undefined symbols for architecture x86_64:
      "antlr4::Lexer::getErrorDisplay(long)", referenced from:
          vtable for CSVLexer in CSVLexer.cpp.o
      "antlr4::Lexer::getCharErrorDisplay(long)", referenced from:
          vtable for CSVLexer in CSVLexer.cpp.o

I downloaded the JAR and C++ runtime from http://www.soft-gems.net/index.php/tools/49-the-antlr4-c-target-is-here today.

Any ideas @mike-lischke  ?

**Comment by mike-lischke** [comment]
I removed    `virtual std::string getErrorDisplay(ssize_t c);` and `virtual std::string getCharErrorDisplay(ssize_t c);` [in this commit](https://github.com/DanMcLaughlin/antlr4/commit/d718fa9f44e36894ffd2d9c05534e81e7f1bfa7f), as they weren't used anywhere in the library code and produced a bit trouble.

Does the CSVLexer use them in an action?

**Comment by nuuman** [comment]
> Does the CSVLexer use them in an action?

No. I haven't changed the CVS grammar at all, and it's very simple:

```
grammar CSV;

file: hdr row+ ;
hdr : row ;

row : field (',' field)* '\r'? '\n' ;

field
    : TEXT
    | STRING
    |
    ;

TEXT   : ~[,\n\r"]+ ;
STRING : '"' ('""'|~'"')* '"' ; // quote-quote is an escaped quote

```

**Comment by nuuman** [comment]
This is my fault, the binary distro obviously didn't update the header files, so I was compiling with old headers.

I'm closing this.
