### ISSUE TITLE
CMake output directory

### ISSUE THREAD

**Issue by nuuman** [DanMcLaughlin/antlr4#8]
I open the CMake file in various IDE's as well as from the command line. Works fine on OS X at least, but the output directory is all over the place, depending on IDE. For instance, CLion puts it in a generated cache directory relative to the IDE install directory.

Would it be possible to update CMakeFiles.txt to specify CMAKE_RUNTIME_OUTPUT_DIRECTORY to a directory relative to the antlr4 cpp runtime project?

That would make it much easier to use the produced library binaries :)

**Comment by mike-lischke** [comment]
Can you offer a patch? I'm certainly ready to accept contributions.

**Comment by nuuman** [comment]
I actually tried, but antlr4 utilize two-level CMakeLists.txt files (per subproject), and the stuff I typically do with variables doesn't seem to work. Someone more well-versed in CMake will have to look into it.

**Comment by kosl90** [comment]
I made some changes to `CMakeLists.txt`s. This issue should be fixed, and some other errors. You can try it. Let me known what you think ;)

[CMakeLists.txt.patch.txt](https://github.com/DanMcLaughlin/antlr4/files/372467/CMakeLists.txt.patch.txt)

**Comment by mike-lischke** [comment]
Thanks. Added in revision [d46ef90]

**Comment by mike-lischke** [comment]
@kosl90, in order to accept your patch I have to ask you to sign the contributors list (add yourself to contributors.txt) and send this to me as well.

**Comment by kosl90** [comment]
like this?

[contributors.path.txt](https://github.com/DanMcLaughlin/antlr4/files/375401/contributors.path.txt)

**Comment by mike-lischke** [comment]
Yes, perfect, thanks.
